services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code/src
    environment:
      - OPENROUTER_API_KEY
    command: .venv/bin/uvicorn src.app.main:app --host 0.0.0.0 --port 9000 --reload
